In [1]:
# Load libraries
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('E:/project/ref.csv') #reading csv file

In [3]:
data.describe()

service          proto  flow_FIN_flag_count  fwd_PSH_flag_count  \
count  123117.000000  123117.000000        123117.000000       123117.000000   
mean        0.556446       0.056247             0.101732            0.304840   
std         1.601466       0.232121             0.433786            3.277407   
min         0.000000       0.000000             0.000000            0.000000   
25%         0.000000       0.000000             0.000000            0.000000   
50%         0.000000       0.000000             0.000000            0.000000   
75%         0.000000       0.000000             0.000000            0.000000   
max         9.000000       2.000000            10.000000          753.000000   

       bwd_pkts_payload.max  bwd_pkts_payload.min  fwd_pkts_payload.std  \
count         123117.000000         123117.000000         123117.000000   
mean              36.466548              2.813129              6.415648   
std              167.733587             14.423564             35.635970   
min                0.000000              0.000000              0.000000   
25%                0.000000              0.000000              0.000000   
50%                0.000000              0.000000              0.000000   
75%                0.000000              0.000000              0.000000   
max             4013.000000            548.000000            639.223507   

       bwd_pkts_payload.std  flow_pkts_payload.max  fwd_subflow_pkts  \
count         123117.000000           123117.00000     123117.000000   
mean              18.446862              131.21166          1.433996   
std               84.776842              153.89866          2.182864   
min                0.000000                0.00000          0.000000   
25%                0.000000              120.00000          1.000000   
50%                0.000000              120.00000          1.000000   
75%                0.000000              120.00000          1.000000   
max              880.644172             4013.00000        276.833333   

       bwd_bulk_rate  fwd_subflow_bytes  bwd_init_window_size    Attack_type  
count   1.231170e+05      123117.000000         123117.000000  123117.000000  
mean    3.242938e+04         124.525107           2586.788892       2.829617  
std     4.454864e+05         276.435192           9356.314472       2.471211  
min     0.000000e+00           0.000000              0.000000       0.000000  
25%     0.000000e+00         120.000000              0.000000       2.000000  
50%     0.000000e+00         120.000000              0.000000       2.000000  
75%     0.000000e+00         120.000000              0.000000       2.000000  
max     2.488969e+07       40637.333330          65535.000000      11.000000

In [4]:
# Split-out validation dataset
array = data.values
X = array[:,0:]
y = array[:,13]

In [5]:
feature_cols = ['service','proto','flow_FIN_flag_count','fwd_PSH_flag_count','bwd_pkts_payload.max','bwd_pkts_payload.min','fwd_pkts_payload.std','bwd_pkts_payload.std','flow_pkts_payload.max','fwd_subflow_pkts','bwd_bulk_rate','fwd_subflow_bytes','bwd_init_window_size','Attack_type']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [7]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

In [8]:
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

RandomForestClassifier()

In [9]:
y_pred=clf.predict(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Instantiate the Random Forest classifier
random_forest = RandomForestClassifier(n_jobs=-1, random_state=15)

# Train the Random Forest classifier using training data
random_forest.fit(X_train, y_train)

# Evaluation
y_pred_test = random_forest.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred_test)
precision = precision_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)

# Confusion Matrix
CM = confusion_matrix(y_true=y_test, y_pred=y_pred_test)

# Extract TP, TN, FP, FN from confusion matrix
TP = np.diag(CM).sum()
FP = CM.sum(axis=0).sum() - TP
FN = CM.sum(axis=1).sum() - TP
TN = CM.sum().sum() - (TP + FP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("True Positives (TP):", TP)
print("True Negatives (TN):", TN)
print("False Positives (FP):", FP)
print("False Negatives (FN):", FN)
print("Confusion Matrix:\n", CM)


Accuracy: 0.9997292614251678
Precision: 0.9997311552481201
Recall: 0.9997292614251678
True Positives (TP): 36926
True Negatives (TN): -10
False Positives (FP): 10
False Negatives (FN): 10
Confusion Matrix:
 [[ 2365     0     0     0     0     0     0     0     0     0     0     0]
 [    0   162     0     0     0     0     0     0     0     0     0     0]
 [    0     0 28436     0     0     0     0     0     0     0     0     0]
 [    0     0     1     8     0     0     1     0     0     0     0     0]
 [    0     0     0     0  1229     0     0     0     0     0     0     0]
 [    0     0     0     0     0     4     6     0     0     0     0     0]
 [    0     0     0     0     1     0   616     0     0     0     0     0]
 [    0     0     0     0     0     0     0   287     0     0     0     0]
 [    0     0     0     0     0     0     0     0   751     1     0     0]
 [    0     0     0     0     0     0     0     0     0   592     0     0]
 [    0     0     0     0     0     0     0

In [11]:
#10x4 VALIDATION-------------> Random Forest
from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import RandomForestClassifier

data = pd.read_csv('E:/project/ref.csv') #reading csv file
X = data.drop(columns=['Attack_type'])  # Assuming 'Attack_type' is the target variable
y = data['Attack_type']

# Define the model (replace with your desired model)
model = RandomForestClassifier()

# Define 10-fold cross-validation with 4 repetitions
kf = KFold(n_splits=10, shuffle=True, random_state=42)  # 10 folds
repetitions = 4

# Perform cross-validation
cv_results = []
for i in range(repetitions):
    cv_scores = cross_val_score(model, X, y, cv=kf)
    cv_results.append(cv_scores)

# Convert the list of arrays into a numpy array for easier manipulation
cv_results = np.array(cv_results)

# Print the results
for i in range(repetitions):
    print(f"Repetition {i+1}: Mean Accuracy: {np.mean(cv_results[i]):.2f}, Std Deviation: {np.std(cv_results[i]):.2f}")

Repetition 1: Mean Accuracy: 0.85, Std Deviation: 0.00
Repetition 2: Mean Accuracy: 0.85, Std Deviation: 0.00
Repetition 3: Mean Accuracy: 0.85, Std Deviation: 0.00
Repetition 4: Mean Accuracy: 0.85, Std Deviation: 0.00


In [12]:
#LOGISTIC REGRESSION

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Instantiate the Logistic Regression classifier
logistic_regression = LogisticRegression(random_state=15, solver='liblinear')

# Train the Logistic Regression classifier using training data
logistic_regression.fit(X_train, y_train)

# Evaluation
y_pred_test = logistic_regression.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred_test)
precision = precision_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)

# Confusion Matrix
CM = confusion_matrix(y_true=y_test, y_pred=y_pred_test)

# Extract TP, TN, FP, FN from confusion matrix
TP = np.diag(CM).sum()
FP = CM.sum(axis=0).sum() - TP
FN = CM.sum(axis=1).sum() - TP
TN = CM.sum().sum() - (TP + FP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("True Positives (TP):", TP)
print("True Negatives (TN):", TN)
print("False Positives (FP):", FP)
print("False Negatives (FN):", FN)
print("Confusion Matrix:\n", CM)


Accuracy: 0.8654700021659086
Precision: 0.7833446550745623
Recall: 0.8654700021659086
True Positives (TP): 31967
True Negatives (TN): -4969
False Positives (FP): 4969
False Negatives (FN): 4969
Confusion Matrix:
 [[    0     0  2365     0     0     0     0     0     0     0     0     0]
 [    0     0   162     0     0     0     0     0     0     0     0     0]
 [    0     0 28238     0   129     0    68     1     0     0     0     0]
 [    0     0     2     0     5     0     0     0     1     2     0     0]
 [    0     0   259     5   752     0     1     5    60     8   139     0]
 [    0     0     1     0     7     0     0     0     1     1     0     0]
 [    0     0    27     0    68     0     1     0   507     4    10     0]
 [    0     0     3     0     0     0     0     0   282     0     2     0]
 [    0     0     0     0     1     0     0     0   749     0     2     0]
 [    0     0    28     0    12     0     0     0   283     1   268     0]
 [    0     0    95     0    58     0

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [14]:
#10x4 validation ------> Logistic Regression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression  # Import Logistic Regression, replace with your desired model
data = pd.read_csv('E:/project/ref.csv') #reading csv file

# Separate features and target variable
X = data.drop(columns=['Attack_type'])  # Assuming 'Attack_type' is the target variable
y = data['Attack_type']

# Define the model (replace with your desired model)
model = LogisticRegression()

# Define 10-fold cross-validation with 4 repetitions
kf = KFold(n_splits=10, shuffle=True, random_state=42)  # 10 folds
repetitions = 4

# Perform cross-validation
cv_results = []
for i in range(repetitions):
    cv_scores = cross_val_score(model, X, y, cv=kf)
    cv_results.append(cv_scores)

# Convert the list of arrays into a numpy array for easier manipulation
cv_results = np.array(cv_results)

# Print the results
for i in range(repetitions):
    print(f"Repetition {i+1}: Mean Accuracy: {np.mean(cv_results[i]):.2f}, Std Deviation: {np.std(cv_results[i]):.2f}")

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Repetition 1: Mean Accuracy: 0.77, Std Deviation: 0.00
Repetition 2: Mean Accuracy: 0.77, Std Deviation: 0.00
Repetition 3: Mean Accuracy: 0.77, Std Deviation: 0.00
Repetition 4: Mean Accuracy: 0.77, Std Deviation: 0.00


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
#NAIVE BAYES 

In [16]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Instantiate the Naive Bayes classifier
naive_bayes = GaussianNB()

# Train the Naive Bayes classifier using training data
naive_bayes.fit(X_train, y_train)

# Evaluation
y_pred_test = naive_bayes.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred_test)
precision = precision_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)

# Confusion Matrix
CM = confusion_matrix(y_true=y_test, y_pred=y_pred_test)

# Extract TP, TN, FP, FN from confusion matrix
TP = np.diag(CM).sum()
FP = CM.sum(axis=0).sum() - TP
FN = CM.sum(axis=1).sum() - TP
TN = CM.sum().sum() - (TP + FP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("True Positives (TP):", TP)
print("True Negatives (TN):", TN)
print("False Positives (FP):", FP)
print("False Negatives (FN):", FN)
print("Confusion Matrix:\n", CM)


Accuracy: 0.1846437080355209
Precision: 0.5191580505127366
Recall: 0.1846437080355209
True Positives (TP): 6820
True Negatives (TN): -30116
False Positives (FP): 30116
False Negatives (FN): 30116
Confusion Matrix:
 [[ 2365     0     0     0     0     0     0     0     0     0     0     0]
 [  162     0     0     0     0     0     0     0     0     0     0     0]
 [24707     0  3616     9     3    11    64     0    12     2    12     0]
 [    1     0     2     3     0     3     0     0     1     0     0     0]
 [    0     0   698     0   205     9    31     0    98    39   149     0]
 [    1     0     1     0     0     4     0     0     2     1     1     0]
 [    7     0   284     3     1    27   265     0     9     2    19     0]
 [    0     0   141     0     0     0   105     0    39     0     2     0]
 [    0     0   384     0     0     1   175     0   186     0     6     0]
 [    5     0   285     0    18    12   184     0    79     1     8     0]
 [ 1195     0   781     6   111    

In [17]:
#10x4 validation ------> Naive Bayes

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB  # Import Gaussian Naive Bayes, replace with your desired model

# Load your dataset (replace 'data.csv' with the path to your dataset)
data = pd.read_csv('E:/project/ref.csv') #reading csv file
# Separate features and target variable
X = data.drop(columns=['Attack_type'])  # Assuming 'Attack_type' is the target variable
y = data['Attack_type']

# Define the model (replace with your desired model)
model = GaussianNB()

# Define 10-fold cross-validation with 4 repetitions
kf = KFold(n_splits=10, shuffle=True, random_state=42)  # 10 folds
repetitions = 4

# Perform cross-validation
cv_results = []
for i in range(repetitions):
    cv_scores = cross_val_score(model, X, y, cv=kf)
    cv_results.append(cv_scores)

# Convert the list of arrays into a numpy array for easier manipulation
cv_results = np.array(cv_results)

# Print the results
for i in range(repetitions):
    print(f"Repetition {i+1}: Mean Accuracy: {np.mean(cv_results[i]):.2f}, Std Deviation: {np.std(cv_results[i]):.2f}")

Repetition 1: Mean Accuracy: 0.18, Std Deviation: 0.00
Repetition 2: Mean Accuracy: 0.18, Std Deviation: 0.00
Repetition 3: Mean Accuracy: 0.18, Std Deviation: 0.00
Repetition 4: Mean Accuracy: 0.18, Std Deviation: 0.00


In [18]:
#KNN MODEL

In [19]:
from sklearn.neighbors import KNeighborsClassifier

# KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)
# Train the model
knn_model.fit(X_train, y_train)
# Make predictions on the test set
y_pred = knn_model.predict(X_test)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Instantiate the KNeighborsClassifier
knn_classifier = KNeighborsClassifier()

# Train the KNeighborsClassifier using training data
knn_classifier.fit(X_train, y_train)

# Evaluation
y_pred_test = knn_classifier.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred_test)
precision = precision_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)

# Confusion Matrix
CM = confusion_matrix(y_true=y_test, y_pred=y_pred_test)

# Extract TP, TN, FP, FN from confusion matrix
TP = np.diag(CM).sum()
FP = CM.sum(axis=0).sum() - TP
FN = CM.sum(axis=1).sum() - TP
TN = CM.sum().sum() - (TP + FP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("True Positives (TP):", TP)
print("True Negatives (TN):", TN)
print("False Positives (FP):", FP)
print("False Negatives (FN):", FN)
print("Confusion Matrix:\n", CM)

Accuracy: 0.9875730994152047
Precision: 0.9874493105444557
Recall: 0.9875730994152047
True Positives (TP): 36477
True Negatives (TN): -459
False Positives (FP): 459
False Negatives (FN): 459
Confusion Matrix:
 [[ 2365     0     0     0     0     0     0     0     0     0     0     0]
 [    0   162     0     0     0     0     0     0     0     0     0     0]
 [    0     0 28400     1    17     0     6     1     2     6     3     0]
 [    0     0     8     0     1     0     0     0     0     1     0     0]
 [    0     0     8     0  1126     0     1     1    15     4    74     0]
 [    0     0     5     0     1     0     3     0     0     0     1     0]
 [    0     0    21     2     9     1   578     0     0     3     3     0]
 [    0     0     0     0     5     0     2   251    25     4     0     0]
 [    0     0     0     0     7     0     1     6   723    14     1     0]
 [    0     0     2     0     1     0     0     4    41   543     1     0]
 [    0     0     3     0   137     0   

In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier  # Import KNN classifier, replace with your desired model

# Load your dataset (replace 'data.csv' with the path to your dataset)
data = pd.read_csv('E:/project/ref.csv') #reading csv file


# Separate features and target variable
X = data.drop(columns=['Attack_type'])  # Assuming 'Attack_type' is the target variable
y = data['Attack_type']

# Define the model (replace with your desired model)
model = KNeighborsClassifier()

# Define 10-fold cross-validation with 4 repetitions
kf = KFold(n_splits=10, shuffle=True, random_state=42)  # 10 folds
repetitions = 4

# Perform cross-validation
cv_results = []
for i in range(repetitions):
    cv_scores = cross_val_score(model, X, y, cv=kf)
    cv_results.append(cv_scores)

# Convert the list of arrays into a numpy array for easier manipulation
cv_results = np.array(cv_results)

# Print the results
for i in range(repetitions):
    print(f"Repetition {i+1}: Mean Accuracy: {np.mean(cv_results[i]):.2f}, Std Deviation: {np.std(cv_results[i]):.2f}")


Repetition 1: Mean Accuracy: 0.16, Std Deviation: 0.00
Repetition 2: Mean Accuracy: 0.16, Std Deviation: 0.00
Repetition 3: Mean Accuracy: 0.16, Std Deviation: 0.00
Repetition 4: Mean Accuracy: 0.16, Std Deviation: 0.00


In [22]:
#XGBOOST MODEL

In [23]:
import xgboost as xgb
#from sklearn.metrics import classification_report, accuracy_score

# Convert the float labels to integers
y_train = y_train.astype(int)

# XGBoost model
xgb_model = xgb.XGBClassifier(random_state=42)

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = xgb_model.predict(X_test)

In [24]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Instantiate the XGBoost classifier
xgb_classifier = xgb.XGBClassifier()

# Train the XGBoost classifier using training data
xgb_classifier.fit(X_train, y_train)

# Evaluation
y_pred_test = xgb_classifier.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred_test)
precision = precision_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)

# Confusion Matrix
CM = confusion_matrix(y_true=y_test, y_pred=y_pred_test)

# Extract TP, TN, FP, FN from confusion matrix
TP = np.diag(CM).sum()
FP = CM.sum(axis=0).sum() - TP
FN = CM.sum(axis=1).sum() - TP
TN = CM.sum().sum() - (TP + FP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("True Positives (TP):", TP)
print("True Negatives (TN):", TN)
print("False Positives (FP):", FP)
print("False Negatives (FN):", FN)
print("Confusion Matrix:\n", CM)


Accuracy: 0.9999729261425168
Precision: 0.9999729270945812
Recall: 0.9999729261425168
True Positives (TP): 36935
True Negatives (TN): -1
False Positives (FP): 1
False Negatives (FN): 1
Confusion Matrix:
 [[ 2365     0     0     0     0     0     0     0     0     0     0     0]
 [    0   162     0     0     0     0     0     0     0     0     0     0]
 [    0     0 28436     0     0     0     0     0     0     0     0     0]
 [    0     0     0    10     0     0     0     0     0     0     0     0]
 [    0     0     0     0  1229     0     0     0     0     0     0     0]
 [    0     0     1     0     0     9     0     0     0     0     0     0]
 [    0     0     0     0     0     0   617     0     0     0     0     0]
 [    0     0     0     0     0     0     0   287     0     0     0     0]
 [    0     0     0     0     0     0     0     0   752     0     0     0]
 [    0     0     0     0     0     0     0     0     0   592     0     0]
 [    0     0     0     0     0     0     0   

In [ ]:
#10x4 XGBOOST
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from xgboost import XGBClassifier  # Import XGBoost classifier, replace with your desired model

# Load your dataset (replace 'data.csv' with the path to your dataset)
data = pd.read_csv('E:/project/ref.csv') #reading csv file

# Separate features and target variable
X = data.drop(columns=['Attack_type'])  # Assuming 'Attack_type' is the target variable
y = data['Attack_type']

# Define the model (replace with your desired model)
model = XGBClassifier()

# Define 10-fold cross-validation with 4 repetitions
kf = KFold(n_splits=10, shuffle=True, random_state=42)  # 10 folds
repetitions = 4

# Perform cross-validation
cv_results = []
for i in range(repetitions):
    cv_scores = cross_val_score(model, X, y, cv=kf)
    cv_results.append(cv_scores)

# Convert the list of arrays into a numpy array for easier manipulation
cv_results = np.array(cv_results)

# Print the results
for i in range(repetitions):
    print(f"Repetition {i+1}: Mean Accuracy: {np.mean(cv_results[i]):.2f}, Std Deviation: {np.std(cv_results[i]):.2f}")


In [ ]:
#LINEAR REGRESSION MODEL

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Linear Regression model
linear_model = LinearRegression()

# Train the model
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = linear_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error for Linear Regression:", mse)
print("R-squared (Coefficient of Determination) for Linear Regression:", r2)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression

# Load your dataset (replace 'data.csv' with the path to your dataset)
data = pd.read_csv('E:/project/ref.csv') #reading csv file

# Separate features and target variable
X = data.drop(columns=['Attack_type'])  # Assuming 'target' is the target variable
y = data['Attack_type']

# Define the model
model = LinearRegression()

# Define k-fold cross-validation with 10 folds
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Perform cross-validation
cv_scores = cross_val_score(model, X, y, cv=kf, scoring='neg_mean_squared_error')

# Convert the scores to positive since sklearn returns negative MSE
cv_scores = -cv_scores

# Print the results
print(f"Mean MSE: {np.mean(cv_scores):.2f}")
print(f"Standard Deviation of MSE: {np.std(cv_scores):.2f}")

In [ ]:
#DECISION TREE

In [ ]:
from sklearn.tree import DecisionTreeClassifier
# Decision Tree model
tree_model = DecisionTreeClassifier(random_state=42)

# Train the model
tree_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = tree_model.predict(X_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Instantiate the Decision Tree classifier
decision_tree = DecisionTreeClassifier(random_state=15)

# Train the Decision Tree classifier using training data
decision_tree.fit(X_train, y_train)

# Evaluation
y_pred_test = decision_tree.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred_test)
precision = precision_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)

# Confusion Matrix
CM = confusion_matrix(y_true=y_test, y_pred=y_pred_test)

# Extract TP, TN, FP, FN from confusion matrix
TP = np.diag(CM).sum()
FP = CM.sum(axis=0).sum() - TP
FN = CM.sum(axis=1).sum() - TP
TN = CM.sum().sum() - (TP + FP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("True Positives (TP):", TP)
print("True Negatives (TN):", TN)
print("False Positives (FP):", FP)
print("False Negatives (FN):", FN)
print("Confusion Matrix:\n", CM)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score, KFold
from sklearn.tree import DecisionTreeClassifier  

# Load your dataset (replace 'data.csv' with the path to your dataset)
data = pd.read_csv('E:/project/ref.csv') 

# Separate features and target variable
X = data.drop(columns=['Attack_type'])  
y = data['Attack_type']

# Define the model (replace with your desired model)
model = DecisionTreeClassifier(random_state=42)

# Define 10-fold cross-validation with 4 repetitions
kf = KFold(n_splits=10, shuffle=True, random_state=42)  
repetitions = 4

# Perform cross-validation
cv_results = []
for i in range(repetitions):
    cv_scores = cross_val_score(model, X, y, cv=kf)
    cv_results.append(cv_scores)

# Convert the list of arrays into a numpy array for easier manipulation
cv_results = np.array(cv_results)

# Print the results
for i in range(repetitions):
    print(f"Repetition {i+1}: Mean Accuracy: {np.mean(cv_results[i]):.2f}, Std Deviation: {np.std(cv_results[i]):.2f}")


In [ ]:
#SVC MODEL

In [ ]:
from sklearn.svm import SVC
# SVC model
svc_model = SVC(random_state=42)
# Train the model
svc_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svc_model.predict(X_test)

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Instantiate the Support Vector Classifier
svc_classifier = SVC()

# Train the SVC classifier using training data
svc_classifier.fit(X_train, y_train)

# Evaluation
y_pred_test = svc_classifier.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred_test)
precision = precision_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_true=y_test, y_pred=y_pred_test, average='weighted', zero_division=0)

# Confusion Matrix
CM = confusion_matrix(y_true=y_test, y_pred=y_pred_test)

# Extract TP, TN, FP, FN from confusion matrix
TP = np.diag(CM).sum()
FP = CM.sum(axis=0).sum() - TP
FN = CM.sum(axis=1).sum() - TP
TN = CM.sum().sum() - (TP + FP + FN)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("True Positives (TP):", TP)
print("True Negatives (TN):", TN)
print("False Positives (FP):", FP)
print("False Negatives (FN):", FN)
print("Confusion Matrix:\n", CM)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.svm import SVC  # Import SVC classifier, replace with your desired model

# Load your dataset (replace 'data.csv' with the path to your dataset)
data = pd.read_csv('E:/project/ref.csv') #reading csv file

# Separate features and target variable
X = data.drop(columns=['Attack_type'])  # Assuming 'Attack_type' is the target variable
y = data['Attack_type']

# Define the model (replace with your desired model)
model = SVC()

# Define 10-fold cross-validation with 4 repetitions
kf = KFold(n_splits=10, shuffle=True, random_state=42)  # 10 folds
repetitions = 4

# Perform cross-validation
cv_results = []
for i in range(repetitions):
    cv_scores = cross_val_score(model, X, y, cv=kf)
    cv_results.append(cv_scores)

# Convert the list of arrays into a numpy array for easier manipulation
cv_results = np.array(cv_results)

# Print the results
for i in range(repetitions):
    print(f"Repetition {i+1}: Mean Accuracy: {np.mean(cv_results[i]):.2f}, Std Deviation: {np.std(cv_results[i]):.2f}")